// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK4qNKVMBUf-zUk4bVC4ZnkUr5e4aMzTs',
    appId: '1:14309880181:web:26af961fd4eb108a73a33c',
    messagingSenderId: '14309880181',
    projectId: 'atmos-67323',
    authDomain: 'atmos-67323.firebaseapp.com',
    storageBucket: 'atmos-67323.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLc6uS4_XBdyCyZXOA-tdEa-iCbG-lWw',
    appId: '1:14309880181:android:a1d33706b1a7b99f73a33c',
    messagingSenderId: '14309880181',
    projectId: 'atmos-67323',
    storageBucket: 'atmos-67323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfQqw67x-_dNzdcMK6Enk10tv2z8CoQOo',
    appId: '1:14309880181:ios:0f4156bf804e539673a33c',
    messagingSenderId: '14309880181',
    projectId: 'atmos-67323',
    storageBucket: 'atmos-67323.appspot.com',
    iosClientId: '14309880181-fu9j1a5olkhon8t8mub0cvc71b16tvm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );
}
